# Use an official Python runtime as the base image
FROM python

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the container
COPY dependencies.sh .

# Install the Python dependencies
RUN sh dependencies.sh

# Copy the rest of the application code to the container
COPY . .

# Set the entrypoint command to run the Python application
CMD ["python", "app.py"]

