pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        script {
          // Define your Docker image name and tag
          def imageName = "778168509800.dkr.ecr.ap-southeast-1.amazonaws.com/monolithic:latest"
          def imageTag = "latest"

          // Build the Docker image
          docker.build(imageName + ":" + imageTag)
        }
      }
    }

    stage('Push to ECR') {
      steps {
        script {
          // Log in to ECR {
              sh "aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 778168509800.dkr.ecr.ap-southeast-1.amazonaws.com/monolithic:latest"
        

          // Tag the Docker image for ECR
          sh "docker tag ${imageName}:${imageTag} 778168509800.dkr.ecr.ap-southeast-1.amazonaws.com/monolithic:latest:${imageTag}"

          // Push the Docker image to ECR
          sh "docker push 778168509800.dkr.ecr.ap-southeast-1.amazonaws.com/monolithic:latest:${imageTag}"
        }
      }
    }
  }
}

